[VCDA-3531]: Implement Lazy RDE upgrades to RDE version 1.1.0
vmware/cluster-api-provider-cloud-director pull request #145
Opened 2022-05-17 00:24 UTC by Anirudh9794

* Upgrade the RDE version upon reconciliation
* Create RDE with minimal information
* Add code to reconcile k8sNetwork

Testing done:
* Generate release-manifests for CAPVCD 0.5.1. (provider label should be added)
* install capvcd 0.5.1 and create a cluster
* Upgrade cluster using `clusterctl upgrade apply --contract v1beta1`

2022-05-18 19:12 UTC, sahithi requested changes
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145)* status: 0 of 4 files reviewed, 8 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[`controllers/vcdcluster_controller.go` line 321 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2JLXaw7qlWxmog4_YE:-N2JLXaw7qlWxmog4_YF:b-v6qn9w) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/01c226df2d01f2214114ecd0a25ec7f3fbba26aa/controllers/vcdcluster_controller.go#L321)):*
> ```Go
> 		Name: CAPVCDClusterCniName,
> 	}
> 	if !reflect.DeepEqual(capvcdStatus.K8sNetwork.Cni, cni) {
> ```

CNI needs to go as part of _rde.entity.status.capvcd.ClusterResourceSet_. Please add a TODO and let Tim know about it
@ltimothy7 
___
*[`controllers/vcdcluster_controller.go` line 470 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2JMQ5kA2eUn08Vmxks:-N2JMQ5kA2eUn08Vmxkt:bni3rt5) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/01c226df2d01f2214114ecd0a25ec7f3fbba26aa/controllers/vcdcluster_controller.go#L470)):*
> ```Go
> 			_, err = capvcdRdeManager.ConvertRDE(ctx, infraID)
> 			if err != nil {
> 				log.Error(err, "failed to upgrade RDE", "rdeID", infraID)
> ```

please add src and destn versions in the log statement.
___
*[`pkg/capisdk/defined_entity.go` line 217 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2JMv0QBk96gjB8roEN:-N2JMv0RB21twgIMhDfn:bbovcdo) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/01c226df2d01f2214114ecd0a25ec7f3fbba26aa/pkg/capisdk/defined_entity.go#L217)):*
> ```Go
> //  CAPVCD will reconcile the RDE eventually with proper data by CAPVCD.
> //  The function attempts upgrade multiple times as defined by MaxUpdateRetries to avoid failures due to incorrect ETag during update.
> func (capvcdRdeManager *CapvcdRdeManager) ConvertRDE(ctx context.Context, rdeID string) (*swagger.DefinedEntity, error) {
> ```

Please rename this method to ConvertToLatestRDEVersionFormat() (or) something that conveys a similar meaning
___
*[`pkg/capisdk/defined_entity.go` line 218 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2JNHZQ6twft0myMEO1:-N2JNHZQ6twft0myMEO2:bdji50q) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/01c226df2d01f2214114ecd0a25ec7f3fbba26aa/pkg/capisdk/defined_entity.go#L218)):*
> ```Go
> //  The function attempts upgrade multiple times as defined by MaxUpdateRetries to avoid failures due to incorrect ETag during update.
> func (capvcdRdeManager *CapvcdRdeManager) ConvertRDE(ctx context.Context, rdeID string) (*swagger.DefinedEntity, error) {
> 	definedEntity, currRdeTypeVersion, err := capvcdRdeManager.GetRDEVersion(ctx, rdeID)
> ```

After you retrieve the RDE version, please move the entire below logic to convertFromRDE1_0().

In the future, we may have to add more convertFrom() methods based on RDE version increments.
This ensures future developers to easily spot and edit the code.
___
*[`pkg/capisdk/defined_entity.go` line 218 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2JO0QN3y_vc2x6iFQ2:-N2JO0QN3y_vc2x6iFQ3:bc301qt) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/01c226df2d01f2214114ecd0a25ec7f3fbba26aa/pkg/capisdk/defined_entity.go#L218)):*
> ```Go
> //  The function attempts upgrade multiple times as defined by MaxUpdateRetries to avoid failures due to incorrect ETag during update.
> func (capvcdRdeManager *CapvcdRdeManager) ConvertRDE(ctx context.Context, rdeID string) (*swagger.DefinedEntity, error) {
> 	definedEntity, currRdeTypeVersion, err := capvcdRdeManager.GetRDEVersion(ctx, rdeID)
> ```

definedEntity -> srcRde
currRdeTypeVersion -> srcRdeTypeVersion

This is just to keep it consistent with K8s terminology around conversion.
___
*[`pkg/capisdk/defined_entity.go` line 246 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2JOGj17W8bEpvuPHjR:-N2JOGj17W8bEpvuPHjS:b-dd9dpj) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/01c226df2d01f2214114ecd0a25ec7f3fbba26aa/pkg/capisdk/defined_entity.go#L246)):*
> ```Go
> 		}
> 		// create empty RDE
> 		newEmptyCapvcdEntity := rdeType.CAPVCDEntity{
> ```

newEmptyCapvcdEntity -> dstEmptyCapvcdEntity
___
*[`pkg/capisdk/defined_entity.go` line 258 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2JON3h9lkg9h7yKlwj:-N2JON3iCfgnMWbMIj_C:b-2fdw2l) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/01c226df2d01f2214114ecd0a25ec7f3fbba26aa/pkg/capisdk/defined_entity.go#L258)):*
> ```Go
> 		}
> 
> 		upgradedCapvcdEntity := swagger.DefinedEntity{
> ```

upgradedCapvcdEntity  -> dstCapvcdRde
___
*[`pkg/capisdk/defined_entity.go` line 293 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2JPESP9UMEKRXoKEZS:-N2JPESP9UMEKRXoKEZT:bwpkzh5) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/01c226df2d01f2214114ecd0a25ec7f3fbba26aa/pkg/capisdk/defined_entity.go#L293)):*
> ```Go
> 	}
> 
> 	return nil, fmt.Errorf("failed to upgrade RDE [%s] to version [%s] after [%d] retries",
> ```

What happens when there is really an error like this?

reconcileRDE will still continue to update the old rde with the latest format. It's just the entity type version stays old and some of the old properties that are not present in the newer format will also continue to show up, right?

is my understanding correct?


<!-- Sent from Reviewable.io -->

2022-05-19 07:47 UTC, Anirudh9794 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145)* status: 0 of 4 files reviewed, 8 unresolved discussions (waiting on @arunmk, @ltimothy7, and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 321 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2JLXaw7qlWxmog4_YE:-N2OUwTJ2uN7VMKeULZB:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/01c226df2d01f2214114ecd0a25ec7f3fbba26aa/controllers/vcdcluster_controller.go#L321)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

CNI needs to go as part of _rde.entity.status.capvcd.ClusterResourceSet_. Please add a TODO and let Tim know about it
@ltimothy7 
</blockquote></details>

Done.
___
*[`controllers/vcdcluster_controller.go` line 470 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2JMQ5kA2eUn08Vmxks:-N2QCl9fAwsVBCGXYXKm:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/01c226df2d01f2214114ecd0a25ec7f3fbba26aa/controllers/vcdcluster_controller.go#L470)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

please add src and destn versions in the log statement.
</blockquote></details>

Done.
___
*[`pkg/capisdk/defined_entity.go` line 217 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2JMv0QBk96gjB8roEN:-N2QCqX329G6fKxdp1xD:bi9imfx) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/01c226df2d01f2214114ecd0a25ec7f3fbba26aa/pkg/capisdk/defined_entity.go#L217)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please rename this method to ConvertToLatestRDEVersionFormat() (or) something that conveys a similar meaning
</blockquote></details>

Changed the method name to `ConvertRDE_From_1_0_0_To_1_1_0`
___
*[`pkg/capisdk/defined_entity.go` line 218 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2JO0QN3y_vc2x6iFQ2:-N2QE7qG1NtesVIA5jvg:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/01c226df2d01f2214114ecd0a25ec7f3fbba26aa/pkg/capisdk/defined_entity.go#L218)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

definedEntity -> srcRde
currRdeTypeVersion -> srcRdeTypeVersion

This is just to keep it consistent with K8s terminology around conversion.
</blockquote></details>

Done.
___
*[`pkg/capisdk/defined_entity.go` line 218 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2JNHZQ6twft0myMEO1:-N2QGSoaBfjSiq3-dPSq:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/01c226df2d01f2214114ecd0a25ec7f3fbba26aa/pkg/capisdk/defined_entity.go#L218)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

After you retrieve the RDE version, please move the entire below logic to convertFromRDE1_0().

In the future, we may have to add more convertFrom() methods based on RDE version increments.
This ensures future developers to easily spot and edit the code.
</blockquote></details>

Done.
___
*[`pkg/capisdk/defined_entity.go` line 246 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2JOGj17W8bEpvuPHjR:-N2QGa3sEom0lu-DRN-d:bs7wumb) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/01c226df2d01f2214114ecd0a25ec7f3fbba26aa/pkg/capisdk/defined_entity.go#L246)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

newEmptyCapvcdEntity -> dstEmptyCapvcdEntity
</blockquote></details>

Done.
___
*[`pkg/capisdk/defined_entity.go` line 258 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2JON3h9lkg9h7yKlwj:-N2QGeZyCN_7SXLFl2X0:b3oh8n) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/01c226df2d01f2214114ecd0a25ec7f3fbba26aa/pkg/capisdk/defined_entity.go#L258)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

upgradedCapvcdEntity  -> dstCapvcdRde
</blockquote></details>


Done.
___
*[`pkg/capisdk/defined_entity.go` line 293 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2JPESP9UMEKRXoKEZS:-N2QGxbs1yEoIR84f0PC:b-7yna4g) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/01c226df2d01f2214114ecd0a25ec7f3fbba26aa/pkg/capisdk/defined_entity.go#L293)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

What happens when there is really an error like this?

reconcileRDE will still continue to update the old rde with the latest format. It's just the entity type version stays old and some of the old properties that are not present in the newer format will also continue to show up, right?

is my understanding correct?
</blockquote></details>

No, it won't update the information in the old RDE.
reconcileNormal() first tries to upgrade the RDE. If there is an RDE present and if the upgrade fails, the upgrade is reattempted. Until RDE is upgraded, the other operations like LB Create will not proceed.


<!-- Sent from Reviewable.io -->

2022-05-19 22:59 UTC, arunmk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> in general with some nits

> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-:-N2TXxhk35TMJte6Vr99:b-ezd2uo)* status: 2 of 6 files reviewed, 13 unresolved discussions (waiting on @Anirudh9794, @arunmk, @ltimothy7, and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 42 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2TWPD43T8VQmuqk04R:-N2TWPD43T8VQmuqk04S:b-19n4oe) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c54b0e1e98e082560cc74e2546e5690353745250/controllers/vcdcluster_controller.go#L42)):*
> ```Go
> 
> const (
> 	CAPVCDClusterCniName = "antrea" // TODO: Get the correct value for CNI name
> ```

We probably should ignore the CNI from now on since Antrea is installed using CRS.
___
*[`controllers/vcdcluster_controller.go` line 477 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2TX1F8-GcsZ3kPKMPF:-N2TX1F8-GcsZ3kPKMPG:b-36gwva) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c54b0e1e98e082560cc74e2546e5690353745250/controllers/vcdcluster_controller.go#L477)):*
> ```Go
> 			if err != nil {
> 				log.Error(err, "failed to upgrade RDE", "rdeID", infraID,
> 					"sourceVersion", rde_type_1_0_0.CapvcdRDETypeVersion,
> ```

How are we sure that source is 1.0.0?
___
*[`infrastructure-vcd/v0.8.0/infrastructure-components.yaml` line 41 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2TXDQL1bus8dwS4qS2:-N2TXDQL1bus8dwS4qS3:bvpob5q) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c54b0e1e98e082560cc74e2546e5690353745250/infrastructure-vcd/v0.8.0/infrastructure-components.yaml#L41)):*
> ```YAML
>     schema:
>       openAPIV3Schema:
>         description: VCDCluster is the Schema for the vcdclusters API
> ```

Is this just some extraneous change?
___
*[`infrastructure-vcd/v0.8.0/infrastructure-components.yaml` line 424 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2TXHT5-1yEv221FL5K:-N2TXHT5-1yEv221FL5L:b-99crex) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c54b0e1e98e082560cc74e2546e5690353745250/infrastructure-vcd/v0.8.0/infrastructure-components.yaml#L424)):*
> ```YAML
>                 type: string
>               storageProfile:
>                 description: StorageProfile is the storage profile to be used on this machince
> ```

typo machince
___
*[`infrastructure-vcd/v0.8.0/infrastructure-components.yaml` line 474 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2TXSt15vZVMxukhzID:-N2TXSt15vZVMxukhzIE:b-5w2mqh) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c54b0e1e98e082560cc74e2546e5690353745250/infrastructure-vcd/v0.8.0/infrastructure-components.yaml#L474)):*
> ```YAML
>                       type: string
>                   required:
>                   - lastTransitionTime
> ```

ah, so this is the v1beta1 format?


<!-- Sent from Reviewable.io -->

2022-05-24 14:51 UTC, Anirudh9794 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145)* status: 2 of 12 files reviewed, 12 unresolved discussions (waiting on @arunmk, @ltimothy7, and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 42 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2TWPD43T8VQmuqk04R:-N2qYCFdD_0J4TXNH55o:b-kq00sl) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c54b0e1e98e082560cc74e2546e5690353745250/controllers/vcdcluster_controller.go#L42)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

We probably should ignore the CNI from now on since Antrea is installed using CRS.
</blockquote></details>

Created VCDA-3740 to remove CNI from capvcd RDE
___
*[`controllers/vcdcluster_controller.go` line 477 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2TX1F8-GcsZ3kPKMPF:-N2qUuU50BrxZCqJ4rH_:b-62rao9) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c54b0e1e98e082560cc74e2546e5690353745250/controllers/vcdcluster_controller.go#L477)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

How are we sure that source is 1.0.0?
</blockquote></details>

Yes, we are not sure of the source version. I removed the source version and I am logging only the target version.
___
*[`infrastructure-vcd/v0.8.0/infrastructure-components.yaml` line 41 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2TXDQL1bus8dwS4qS2:-N2qV3nbAPBEukOdFZTZ:b-ig7hqv) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c54b0e1e98e082560cc74e2546e5690353745250/infrastructure-vcd/v0.8.0/infrastructure-components.yaml#L41)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Is this just some extraneous change?
</blockquote></details>

Yes, I think it was reset when I re-generated the manifests.
___
*[`infrastructure-vcd/v0.8.0/infrastructure-components.yaml` line 424 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2TXHT5-1yEv221FL5K:-N2qVcLW3SrlI8epsVCF:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c54b0e1e98e082560cc74e2546e5690353745250/infrastructure-vcd/v0.8.0/infrastructure-components.yaml#L424)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

typo machince
</blockquote></details>

Done.
___
*[`infrastructure-vcd/v0.8.0/infrastructure-components.yaml` line 474 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2TXSt15vZVMxukhzID:-N2qVd4h2mgZq-V9Blsf:b-xf6339) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c54b0e1e98e082560cc74e2546e5690353745250/infrastructure-vcd/v0.8.0/infrastructure-components.yaml#L474)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

ah, so this is the v1beta1 format?
</blockquote></details>

I think so. But I remember Yan pointing out that lastTransitionTime was a required property before. But for some reason it was not added as "required" to the manifests.


<!-- Sent from Reviewable.io -->

2022-05-24 21:47 UTC, sahithi requested changes
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145)* status: 1 of 18 files reviewed, 14 unresolved discussions (waiting on @Anirudh9794, @arunmk, @ltimothy7, and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 477 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2TX1F8-GcsZ3kPKMPF:-N2rMkSV7ZxfnF_nJ7v7:b-qn7orw) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c54b0e1e98e082560cc74e2546e5690353745250/controllers/vcdcluster_controller.go#L477)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Yes, we are not sure of the source version. I removed the source version and I am logging only the target version.
</blockquote></details>

src version is vcdCluster.Status.RdeVersionInUse, please add both src and destn version in all the relevant log statements including reconcile error statements.  I understand that src version will be empty for capvcd 0.5 rdes.

These minor details will come in very handy during debugging.
___
*[`controllers/vcdcluster_controller.go` line 511 at r5](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2rNZ3h7EFhbTIeWlPm:-N2rNZ3h7EFhbTIeWlPn:bgtug6w) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c779cfecf7f6d4b181b4cbab214a2380a6555318/controllers/vcdcluster_controller.go#L511)):*
> ```Go
> 	// After InfraId has been set, we can update parentUid, useAsMgmtCluster status
> 	vcdCluster.Status.UseAsManagementCluster = vcdCluster.Spec.UseAsManagementCluster
> 	vcdCluster.Status.ParentUID = vcdCluster.Spec.ParentUID
> ```

We need to set the  "vcdCluster.status.RdeVersionInUse" value to the latest RDE version for the fresh cluster creations here.
___
*[`pkg/capisdk/defined_entity.go` line 199 at r5](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2rpOMCBh8x0T10SG2L:-N2rpOMD9w2XT2zI0TJO:b-xneqq0) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c779cfecf7f6d4b181b4cbab214a2380a6555318/pkg/capisdk/defined_entity.go#L199)):*
> ```Go
> 		if gsErr, ok := err.(swagger.GenericSwaggerError); ok {
> 			responseMessageBytes = gsErr.Body()
> 			klog.Errorf("error occurred when getting RDE type version for defined entity [%s]: [%s]",
> ```

klog.v(3)....
___
*[`pkg/capisdk/defined_entity.go` line 227 at r5](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2s0L_S7wZJ8R-Vt6fW:-N2s0L_S7wZJ8R-Vt6fX:b-k8cn8) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c779cfecf7f6d4b181b4cbab214a2380a6555318/pkg/capisdk/defined_entity.go#L227)):*
> ```Go
> }
> 
> func (capvcdRdeManager *CapvcdRdeManager) IsCapvcdEntityType_1_1_0_Registered() bool {
> ```

can we parameterize this method with the version?

IsCapvcdEntityTypeVersionRegistered(version). 

That will avoid renaming and refactoring in the future versions of capvcd.
___
*[`pkg/capisdk/defined_entity.go` line 238 at r5](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2rq5qw4CmlKI0QiHw-:-N2rq5qw4CmlKI0QiHw0:b-xfovul) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c779cfecf7f6d4b181b4cbab214a2380a6555318/pkg/capisdk/defined_entity.go#L238)):*
> ```Go
> 		"1.0.0/entityTypes/" + entityTypeID)
> 	if err != nil {
> 		klog.Errorf("failed to construct URL to get list of entity types")
> ```

Please increase the verbosity level in these log statements.
___
*[`pkg/capisdk/defined_entity.go` line 253 at r5](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2ryhbd80TWwB8jV8_C:-N2ryhbd80TWwB8jV8_D:b-8y378i) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c779cfecf7f6d4b181b4cbab214a2380a6555318/pkg/capisdk/defined_entity.go#L253)):*
> ```Go
> }
> 
> func (capvcdRdeManager *CapvcdRdeManager) convertTo_1_1_0_Format(ctx context.Context, srcRde *swagger.DefinedEntity, srcRdeTypeVersion string) (*swagger.DefinedEntity, error) {
> ```

The method name needs to be convertFrom100().

Tomorrow, after version 1.2 comes up, we will add another method convertFrom110() 
and top-level convertToLatestFormat() stays as is and these methods will be internally called based on the vcdcluster.status.rdeVersionInUse version.
___
*[`pkg/capisdk/defined_entity.go` line 312 at r5](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2ryRMa7r1ezrPL-CxQ:-N2ryRMa7r1ezrPL-CxR:b-h11uz3) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c779cfecf7f6d4b181b4cbab214a2380a6555318/pkg/capisdk/defined_entity.go#L312)):*
> ```Go
> 		}
> 
> 		dstCapvcdRde := swagger.DefinedEntity{
> ```

I am not very sure if this is the right way to do it.

For example, by the time code gets here, say CSI and CPI have added their sections in this RDE. Will this code wipe them off?
___
*[`pkg/capisdk/defined_entity.go` line 335 at r5](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2s0mTGA2KbRcnC6JwC:-N2s0mTGA2KbRcnC6JwD:bezoblv) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c779cfecf7f6d4b181b4cbab214a2380a6555318/pkg/capisdk/defined_entity.go#L335)):*
> ```Go
> 		} else {
> 			if resp.StatusCode == http.StatusPreconditionFailed {
> 				klog.Errorf("wrong etag found when upgrading the defined entity [%s] to version [%s]. Retries remaining: [%d]",
> ```

log verbosity level needs to go up
___
*[`pkg/capisdk/defined_entity.go` line 363 at r5](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2s-w9D0YkKHAab4Y4I:-N2s-w9D0YkKHAab4Y4J:b49zwr1) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c779cfecf7f6d4b181b4cbab214a2380a6555318/pkg/capisdk/defined_entity.go#L363)):*
> ```Go
> 		return nil, fmt.Errorf("failed to fetch RDE type version for RDE [%s]", rdeID)
> 	}
> 	dstRde, err := capvcdRdeManager.convertTo_1_1_0_Format(ctx, srcRde, srcRdeTypeVersion)
> ```

if srcRdeVersion = 1.0.0 
     capvcdRdeManager.convertFrom1_0_0()


<!-- Sent from Reviewable.io -->

2022-05-25 14:40 UTC, Anirudh9794 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145)* status: 1 of 18 files reviewed, 14 unresolved discussions (waiting on @arunmk, @ltimothy7, and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 477 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2TX1F8-GcsZ3kPKMPF:-N2sgu675wVqXYb63g_r:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c54b0e1e98e082560cc74e2546e5690353745250/controllers/vcdcluster_controller.go#L477)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

src version is vcdCluster.Status.RdeVersionInUse, please add both src and destn version in all the relevant log statements including reconcile error statements.  I understand that src version will be empty for capvcd 0.5 rdes.

These minor details will come in very handy during debugging.
</blockquote></details>

Done.
___
*[`controllers/vcdcluster_controller.go` line 511 at r5](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2rNZ3h7EFhbTIeWlPm:-N2s2Va3EpWjoe622exe:b-qpj06s) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c779cfecf7f6d4b181b4cbab214a2380a6555318/controllers/vcdcluster_controller.go#L511)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We need to set the  "vcdCluster.status.RdeVersionInUse" value to the latest RDE version for the fresh cluster creations here.
</blockquote></details>

Ah, yes, i missed this. Thanks for catching this
___
*[`pkg/capisdk/defined_entity.go` line 199 at r5](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2rpOMCBh8x0T10SG2L:-N2sh6kpETE0R1ImJk9H:b-rrgyqo) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c779cfecf7f6d4b181b4cbab214a2380a6555318/pkg/capisdk/defined_entity.go#L199)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

klog.v(3)....
</blockquote></details>

klog.V(3).Errorf() doesn't exist.
___
*[`pkg/capisdk/defined_entity.go` line 227 at r5](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2s0L_S7wZJ8R-Vt6fW:-N2si62m0Zliv43q8LQp:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c779cfecf7f6d4b181b4cbab214a2380a6555318/pkg/capisdk/defined_entity.go#L227)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

can we parameterize this method with the version?

IsCapvcdEntityTypeVersionRegistered(version). 

That will avoid renaming and refactoring in the future versions of capvcd.
</blockquote></details>

Done.
___
*[`pkg/capisdk/defined_entity.go` line 238 at r5](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2rq5qw4CmlKI0QiHw-:-N2si8dA6-EXTfME7M5Y:b-w3hqd3) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c779cfecf7f6d4b181b4cbab214a2380a6555318/pkg/capisdk/defined_entity.go#L238)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please increase the verbosity level in these log statements.
</blockquote></details>

Can't increase verbosity level for error logs.
___
*[`pkg/capisdk/defined_entity.go` line 253 at r5](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2ryhbd80TWwB8jV8_C:-N2siyuLA_Gbtp-BvXfk:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c779cfecf7f6d4b181b4cbab214a2380a6555318/pkg/capisdk/defined_entity.go#L253)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

The method name needs to be convertFrom100().

Tomorrow, after version 1.2 comes up, we will add another method convertFrom110() 
and top-level convertToLatestFormat() stays as is and these methods will be internally called based on the vcdcluster.status.rdeVersionInUse version.


</blockquote></details>

Done.
___
*[`pkg/capisdk/defined_entity.go` line 312 at r5](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2ryRMa7r1ezrPL-CxQ:-N2skDKV7E_Ri-wAyDp_:bx9y5sb) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c779cfecf7f6d4b181b4cbab214a2380a6555318/pkg/capisdk/defined_entity.go#L312)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I am not very sure if this is the right way to do it.

For example, by the time code gets here, say CSI and CPI have added their sections in this RDE. Will this code wipe them off?
</blockquote></details>

As discussed, I have left the code as is but implemented a way to specify a list to retain specific sections of status
___
*[`pkg/capisdk/defined_entity.go` line 335 at r5](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2s0mTGA2KbRcnC6JwC:-N2st-B37x16eMwCPPdZ:b6rm55w) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c779cfecf7f6d4b181b4cbab214a2380a6555318/pkg/capisdk/defined_entity.go#L335)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

log verbosity level needs to go up
</blockquote></details>

Verbosity of error logs can't be changed
___
*[`pkg/capisdk/defined_entity.go` line 363 at r5](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2s-w9D0YkKHAab4Y4I:-N2swylj8FX3-581ANLR:bov9itc) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/c779cfecf7f6d4b181b4cbab214a2380a6555318/pkg/capisdk/defined_entity.go#L363)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

if srcRdeVersion = 1.0.0 
     capvcdRdeManager.convertFrom1_0_0()
</blockquote></details>

Done. Used a switch statement instead.


<!-- Sent from Reviewable.io -->

2022-05-25 19:47 UTC, sahithi requested changes
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145)* status: 1 of 18 files reviewed, 7 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[`api/v1beta1/vcdcluster_types.go` line 93 at r7](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2wjSda6Co5Xs-P68tP:-N2wjSda6Co5Xs-P68tQ:b-qhzr8z) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f0c3d22dcc785f41b5222e87241ba99b48e93a44/api/v1beta1/vcdcluster_types.go#L93)):*
> ```Go
> 	// RdeVersionInUse indicates the version of capvcdCluster entity type used by CAPVCD.
> 	// +kubebuilder:default="1.0.0"
> 	RdeVersionInUse string `json:"rdeVersionInUse"`
> ```

Let us say below steps are performed
1. capvcd 0.5.x cluster is created
2. clusterctl upgrade command is run
3. Now as capvcd can process only v1beta1 formats, webhook gets called before every reconcile trigger.

In that process, does the default value for the  above property in the existing objects be 1.0.0, if yes, rde upgrade logic will never get run.

Please check this case.
___
*[`pkg/capisdk/defined_entity.go` line 34 at r7](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2wfpBf3eEx270C9fQ-:-N2wfpBf3eEx270C9fQ0:b-74q2xe) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f0c3d22dcc785f41b5222e87241ba99b48e93a44/pkg/capisdk/defined_entity.go#L34)):*
> ```Go
> 
> var (
> 	sectionsInStatusRetainedDuringRDEUpgrade = []string{
> ```

this must include CSI and CPI as well.

Please also add a detailed comment for this variable, it may not be obvious to new readers.

During upgrade from any old rde to a newer version format, we must be careful not to wipe out sections maintained by other components like CSI, CPI, VKP. Those sections can have their own upgrade logic independent of capvcd's upgrades. Below is the retain list of the sections in "status" that CAPVCD should not touch.


<!-- Sent from Reviewable.io -->

2022-05-25 20:17 UTC, sahithi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-:-N2wrPJP-ycCBDYDw07Z:bg7igkv)* status: 1 of 18 files reviewed, 8 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[`api/v1alpha4/vcdcluster_conversion.go` line 19 at r7](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2wpssV4BVw6gcXpRxt:-N2wpssV4BVw6gcXpRxu:b5u5irb) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f0c3d22dcc785f41b5222e87241ba99b48e93a44/api/v1alpha4/vcdcluster_conversion.go#L19)):*
> ```Go
> 	dst.Spec.ParentUID = ""
> 	dst.Spec.UseAsManagementCluster = false
> 	dst.Status.RdeVersionInUse = ""
> ```

We can set this to 1.0.0.
___
*[`api/v1beta1/vcdcluster_types.go` line 93 at r7](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/145#-N2wjSda6Co5Xs-P68tP:-N2wrFGmE37tvhfnabpC:b-2ealv3) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f0c3d22dcc785f41b5222e87241ba99b48e93a44/api/v1beta1/vcdcluster_types.go#L93)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Let us say below steps are performed
1. capvcd 0.5.x cluster is created
2. clusterctl upgrade command is run
3. Now as capvcd can process only v1beta1 formats, webhook gets called before every reconcile trigger.

In that process, does the default value for the  above property in the existing objects be 1.0.0, if yes, rde upgrade logic will never get run.

Please check this case.
</blockquote></details>

If there is going to be any default value, this needs to be 1.1.0


<!-- Sent from Reviewable.io -->

2022-05-26 15:35 UTC, merged