fix: the script to get etcd and coredns version
vmware/cluster-api-provider-cloud-director pull request #323
Opened 2022-10-27 16:27 UTC by viveksyngh

When I tried to run the script on my system it failed with different errors
- As  */layer.tar not quoted it returns (no matches found: */layer.tar)
- yq commands errors as below (yq: error: argument files: can't open '.components.etcd[0].images.etcd.tag': [Errno 2] No such file or directory: '.components.etcd[0].images.etcd.tag')

## Description
Please provide a brief description of the changes proposed in this Pull Request

- When you try to run previous version it results in below errors 
```
Error response from daemon: unknown: artifact tkg/tkr-bom:v1.20.8_vmware.1-tkg.1 not found
v1.20.8_vmware.1-tkg.2: Pulling from tkg/tkr-bom
Digest: sha256:f6f1b8e3ba86b41a035ac9c8489dcf8bac0fbac3e856c32b885a68db63aaa35b
Status: Image is up to date for projects.registry.vmware.com/tkg/tkr-bom:v1.20.8_vmware.1-tkg.2
projects.registry.vmware.com/tkg/tkr-bom:v1.20.8_vmware.1-tkg.2
zsh: no matches found: */layer.tar
usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
          [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
          [--indentless-lists] [--in-place] [--version]
          [jq_filter] [files ...]
yq: error: argument files: can't open '.components.etcd[0].version': [Errno 2] No such file or directory: '.components.etcd[0].version'
usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
          [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
          [--indentless-lists] [--in-place] [--version]
          [jq_filter] [files ...]
yq: error: argument files: can't open '.components.etcd[0].images.etcd.imagePath': [Errno 2] No such file or directory: '.components.etcd[0].images.etcd.imagePath'
usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
          [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
          [--indentless-lists] [--in-place] [--version]
          [jq_filter] [files ...]
yq: error: argument files: can't open '.components.etcd[0].images.etcd.tag': [Errno 2] No such file or directory: '.components.etcd[0].images.etcd.tag'
usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
          [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
          [--indentless-lists] [--in-place] [--version]
          [jq_filter] [files ...]
yq: error: argument files: can't open '.components.coredns[0].version': [Errno 2] No such file or directory: '.components.coredns[0].version'
usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
          [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
          [--indentless-lists] [--in-place] [--version]
          [jq_filter] [files ...]
yq: error: argument files: can't open '.components.coredns[0].images.coredns.imagePath': [Errno 2] No such file or directory: '.components.coredns[0].images.coredns.imagePath'
usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
          [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
          [--indentless-lists] [--in-place] [--version]
          [jq_filter] [files ...]
yq: error: argument files: can't open '.components.coredns[0].images.coredns.tag': [Errno 2] No such file or directory: '.components.coredns[0].images.coredns.tag'

```

But with new changes it works fine.

```
Error response from daemon: unknown: artifact tkg/tkr-bom:v1.20.8_vmware.1-tkg.1 not found
v1.20.8_vmware.1-tkg.2: Pulling from tkg/tkr-bom
Digest: sha256:f6f1b8e3ba86b41a035ac9c8489dcf8bac0fbac3e856c32b885a68db63aaa35b
Status: Image is up to date for projects.registry.vmware.com/tkg/tkr-bom:v1.20.8_vmware.1-tkg.2
projects.registry.vmware.com/tkg/tkr-bom:v1.20.8_vmware.1-tkg.2
ETCD_VERSION: v3.4.13_vmware.14
ETCD_IMAGE_PATH: projects.registry.vmware.com/tkg/etcd
ETCD_IMAGE_TAG: v3.4.13_vmware.14
COREDNS_VERSION: v1.7.0_vmware.12
COREDNS_IMAGE_PATH: projects.registry.vmware.com/tkg/coredns
COREDNS_IMAGE_TAG: v1.7.0_vmware.12
```
## Checklist
- [x ] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [ ] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

2022-11-01 19:44 UTC, ymo24 requested changes
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/323)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @viveksyngh)

___
*[`docs/WORKLOAD_CLUSTER.md` line 168 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/323#-NFohUrfDwsErr1_H700:-NFohUrfDwsErr1_H701:b-rppage) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/bb7f77d7ec3a8d716e3bc7826becbc578a7c84fc/docs/WORKLOAD_CLUSTER.md#L168)):*
> ```Markdown
> docker save projects.registry.vmware.com/tkg/tkr-bom:${K8S_VERSION} | tar Oxf - --strip-components 1 '*/layer.tar' | tar xf -
> 
> ETCD_VERSION=$(yq  -r ".components.etcd[0].version" tkr-bom-${K8S_VERSION_RAW}.yaml | tr -s "+" "_")
> ```

Hi Vivek, you saw this error (yq: error: argument files: can't open '.components.etcd[0].images.etcd.tag': [Errno 2] No such file or directory: '.components.etcd[0].images.etcd.tag') because this K8S_VERSION_RAW was tkg/tkr-bom:v1.20.8_vmware.1-tkg.1 and it is not found. The download file name is tkg/tkr-bom:v1.20.8_vmware.1-tkg.2.yaml. So if you modify K8S_VERSION_RAW, you will find out our commands work


<!-- Sent from Reviewable.io -->

2023-03-01 19:23 UTC, arunmk commented
@viveksyngh does @ymo24 's comment make sense? If so, can we close this ticket

2023-03-03 09:31 UTC, viveksyngh commented
We can close this if it works. I will take latest pull and try it again.

2023-03-04 17:56 UTC, arunmk commented
Closed based on recent comments.

2023-03-04 17:56 UTC, closed without merging