[CAFV-153] Package manifests files when new images are pushed
vmware/cluster-api-provider-cloud-director pull request #379
Opened 2023-02-03 01:21 UTC by lzichong

Signed-off-by: lzichong <lzichong@vmware.com>

## Description
Please provide a brief description of the changes proposed in this Pull Request

- Packages infrastructure-components.yaml, metadata.yaml into it's own container each time new dev/prod images are pushed
- Testings done:
  - `make prod` – pushes to `harbor-repo.vmware.com/vcloud/capvcd-manifest-airgapped:{version}`, with `__REGISTRY__` placeholders in manifest, pointing to `harbor-repo.vmware.com/vcloud/cluster-api-provider-cloud-director:{version}`
  - `make dev` – similar as prod, but uses commit and pushes to `harbor-repo.vmware.com/vcloud/capvcd-manifest-airgapped:{gitCommitSha}`. 

- Updated `manager.yaml.template` to use `__REGISTRY__`, and only replace with actual registry when pushing CAPVCD images, so that default infrastructure-components.yaml will use the $REGISTRY stored in Makefile
 

## Checklist
- [x] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [x] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

2023-02-04 00:00 UTC, rocknes requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/379)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794, @arunmk, @lzichong, and @sakthisunda)

___
*[`Makefile` line 198 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/379#-NNOhllG8cUk6uKwRCM0:-NNOhllG8cUk6uKwRCM1:b5q9wds) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/fcbe61f8b6e55b52e9a30e034a872911fd9df550/Makefile#L198)):*
> ```Makefile
> 	sed -e "s/\.__GIT_COMMIT__//g" -e "s/__VERSION__/$(version)/g" config/manager/manager.yaml.template > config/manager/manager.yaml
> 	make release-manifests
> 	cp templates/infrastructure-components.yaml ./artifacts/infrastructure-components-airgap.yaml.template
> ```

Do we really need to copy this file.

As far as I understand the copy of the yaml file we are hosting on github should be done away with as soon as the last installation of CSE 4.0 is decommissioned. I would suggest to straight up maintain a copy of the file in artifacts folder.

I don't see any changes being made to the file in templates folder in future. If any change ever needs to be made, it should go in the copy of the file in the artifacts directory. This becomes the source of truth from now on.


<!-- Sent from Reviewable.io -->

2023-02-04 01:25 UTC, lzichong reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/379)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794, @arunmk, @sahithi, and @sakthisunda)

___
*[`Makefile` line 198 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/379#-NNOhllG8cUk6uKwRCM0:-NNOveDq53SNLaxGMtkK:bfjnrv5) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/fcbe61f8b6e55b52e9a30e034a872911fd9df550/Makefile#L198)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Do we really need to copy this file.

As far as I understand the copy of the yaml file we are hosting on github should be done away with as soon as the last installation of CSE 4.0 is decommissioned. I would suggest to straight up maintain a copy of the file in artifacts folder.

I don't see any changes being made to the file in templates folder in future. If any change ever needs to be made, it should go in the copy of the file in the artifacts directory. This becomes the source of truth from now on.
</blockquote></details>

I am okay with moving it to artifacts. I had separated it because the infrastructure-components file could change based on new fields as CRDs could get updated also, which then the `.template` file is also subject to change. The copy is also more for the CAPVCD standalone users where they use clusterctl manually. By separating the yaml and template file they don't need to do an additional step of replacing the registry themselves as a clusterctl variable. Though we can also mitigate this by using releases and provide the infrastructure-components.yaml there. I think this would probably best checked with @sahithi 


<!-- Sent from Reviewable.io -->

2023-02-14 17:46 UTC, rocknes approved these changes

2023-02-15 18:07 UTC, sakthisunda approved these changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/379)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794, @arunmk, and @sahithi)



<!-- Sent from Reviewable.io -->

2023-02-16 18:59 UTC, merged