Skip RDE upgrades if VCDKECluster is True
vmware/cluster-api-provider-cloud-director pull request #454
Opened 2023-05-23 22:35 UTC by ymo24

## Description
Please provide a brief description of the changes proposed in this Pull Request

- Skip RDE upgrades if VCDKECluster is True
- Standalone capvcd cluster - RDE upgrades should happen and status updates must happen.
- VCD-KE cluster - RDE upgrades should not happen and but status updates must happen

## Checklist
- [x] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [ ] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

2023-05-23 23:29 UTC, Anirudh9794 requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454)* status: all files reviewed, 5 unresolved discussions (waiting on @sahithi and @ymo24)

___
*[`controllers/vcdcluster_controller.go` line 809 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NW9pNt1-aC0dqVSBDsQ:-NW9pNt1-aC0dqVSBDsR:b22exdy) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e7690aac99a6a18648b51164eddaa12967844126/controllers/vcdcluster_controller.go#L809)):*
> ```Go
> 		}
> 
> 		//1. If infraID indicates that there is no RDE (Resource Definition Entity), skip the RDE upgrade process.
> ```

RDE in VCD is Runtime Defined Entity
___
*[`controllers/vcdcluster_controller.go` line 817 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NW9rXK432FDeKI5HUCg:-NW9rXK432FDeKI5HUCh:b-916xjo) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e7690aac99a6a18648b51164eddaa12967844126/controllers/vcdcluster_controller.go#L817)):*
> ```Go
> 			isVCDKECluster, err := capvcdRdeManager.IsVCDKECluster(ctx, infraID)
> 			if err != nil {
> 				return ctrl.Result{}, errors.Wrapf(err, "error occurred when checking whether the RDE is vcdKE Cluster [%s]", infraID)
> ```

we are blocking execution of CAPVCD if vcdKeSpec section is present but the vcdKeSpec is not present in an expected format.

I am not sure if we should do this. 

Can we not say that if the vcdKeSpec section is present and if `isVcdKeCluster` flag is absent, then the cluster is not managed by CSE? Because CSE won't process these clusters anyways.

I think we should just return true / false for isVcdKeCluster() and skip this error check.
___
*[`controllers/vcdcluster_controller.go` line 821 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NW9vZMjDFzBhvvXMMFf:-NW9vZMjDFzBhvvXMMFg:b-9d1aos) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e7690aac99a6a18648b51164eddaa12967844126/controllers/vcdcluster_controller.go#L821)):*
> ```Go
> 			// 4. Skip the RDE upgrade process if the VCDKECluster flag is set to true
> 			//    and current_rde_version < standard_rde_version
> 			if !isVCDKECluster && capisdk.CheckIfRdeVersionNeedsUpgraded(vcdCluster.Status.RdeVersionInUse, rdeType.CapvcdRDETypeVersion) {
> ```

Can we use the variable `rdeVersionInUse` instead of `vcdCluster.Status.RdeVersionInUse` ?
___
*[`pkg/capisdk/defined_entity.go` line 131 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NW9wJip1eB9wlXR1xOt:-NW9wJip1eB9wlXR1xOu:bk6nr17) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e7690aac99a6a18648b51164eddaa12967844126/pkg/capisdk/defined_entity.go#L131)):*
> ```Go
> 	entityTypeSemVer, err := semver.New(srcRdeTypeVersion)
> 	if err != nil {
> 		klog.Errorf("fail to convert [%s] into a standard version: [%v]", srcRdeTypeVersion, err)
> ```

missing `return false` here?
___
*[`pkg/capisdk/defined_entity.go` line 135 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NW9wP1r81DYWyd72q6_:-NW9wP1r81DYWyd72q6a:bbdevwg) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e7690aac99a6a18648b51164eddaa12967844126/pkg/capisdk/defined_entity.go#L135)):*
> ```Go
> 	tgtRdeTypeVersionSemVer, err := semver.New(tgtRdeTypeVersion)
> 	if err != nil {
> 		klog.Errorf("fail to convert [%s] into a standard version: [%v]", srcRdeTypeVersion, err)
> ```

missing `return false` here as well


<!-- Sent from Reviewable.io -->

2023-05-23 23:46 UTC, ymo24 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 809 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NW9pNt1-aC0dqVSBDsQ:-NW9zuhV7dxSHgf1dvub:b-896fix) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e7690aac99a6a18648b51164eddaa12967844126/controllers/vcdcluster_controller.go#L809)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

RDE in VCD is Runtime Defined Entity
</blockquote></details>

Done.
___
*[`controllers/vcdcluster_controller.go` line 817 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NW9rXK432FDeKI5HUCg:-NW9ybIu90bARRo9sd75:byjue63) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e7690aac99a6a18648b51164eddaa12967844126/controllers/vcdcluster_controller.go#L817)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

we are blocking execution of CAPVCD if vcdKeSpec section is present but the vcdKeSpec is not present in an expected format.

I am not sure if we should do this. 

Can we not say that if the vcdKeSpec section is present and if `isVcdKeCluster` flag is absent, then the cluster is not managed by CSE? Because CSE won't process these clusters anyways.

I think we should just return true / false for isVcdKeCluster() and skip this error check.

</blockquote></details>

Understood. If the vcdKeSpec section is not presented, the function will just return false, nil.
IsVCDKECluster() will return an error only when RDE itself has some issues.
I will change this function to return just a boolean result. Thanks for the reminder.
___
*[`pkg/capisdk/defined_entity.go` line 131 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NW9wJip1eB9wlXR1xOt:-NW9zohaByHiL8qdfnna:b3hwd1y) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e7690aac99a6a18648b51164eddaa12967844126/pkg/capisdk/defined_entity.go#L131)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

missing `return false` here?
</blockquote></details>

Thanks, Aniruddha
___
*[`pkg/capisdk/defined_entity.go` line 135 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NW9wP1r81DYWyd72q6_:-NW9zr3J5NZygY5Rpzp6:b-cguh4x) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e7690aac99a6a18648b51164eddaa12967844126/pkg/capisdk/defined_entity.go#L135)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

missing `return false` here as well
</blockquote></details>

Thanks for the catching


<!-- Sent from Reviewable.io -->

2023-05-24 00:19 UTC, ymo24 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 821 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NW9vZMjDFzBhvvXMMFf:-NWA0Vdr-pU-TYPcIVYx:bdfr3id) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e7690aac99a6a18648b51164eddaa12967844126/controllers/vcdcluster_controller.go#L821)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Can we use the variable `rdeVersionInUse` instead of `vcdCluster.Status.RdeVersionInUse` ?
</blockquote></details>

It should be the same.
I chose to use `vcdCluster.Status.RdeVersionInUse` as I used it in the first check (what you mentioned is the second check). `vcdCluster.Status.RdeVersionInUse` has a slight difference from `rdeVersionInUse`: we want to upgrade RDE only on existing CAPVCD clusters. `vcdCluster.Status.RdeVersionInUse` could be empty while `rdeVersionInUse` should always be the entity type version of the RDE (it always be non-empty).

I used  `vcdCluster.Status.RdeVersionInUse` here for consistency. Let me know your thoughts. Thanks Aniruddha!



_Code snippet:_
```Go
!strings.Contains(infraID, NoRdePrefix) && vcdCluster.Status.RdeVersionInUse != "" &&
			vcdCluster.Status.RdeVersionInUse != rdeType.CapvcdRDETypeVersion {
					if !isVCDKECluster && capisdk.CheckIfRdeVersionNeedsUpgraded(vcdCluster.Status.RdeVersionInUse, rdeType.CapvcdRDETypeVersion) {
						...
					}
				
				}
```


<!-- Sent from Reviewable.io -->

2023-05-24 20:11 UTC, sahithi reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454)* status: 0 of 2 files reviewed, 8 unresolved discussions (waiting on @Anirudh9794 and @ymo24)

___
*[`controllers/vcdcluster_controller.go` line 821 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NW9vZMjDFzBhvvXMMFf:-NWEFIn-5FGyZfHdZLyy:b-klhv89) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e7690aac99a6a18648b51164eddaa12967844126/controllers/vcdcluster_controller.go#L821)):*
<details><summary><i>Previously, ymo24 wrote…</i></summary><blockquote>

It should be the same.
I chose to use `vcdCluster.Status.RdeVersionInUse` as I used it in the first check (what you mentioned is the second check). `vcdCluster.Status.RdeVersionInUse` has a slight difference from `rdeVersionInUse`: we want to upgrade RDE only on existing CAPVCD clusters. `vcdCluster.Status.RdeVersionInUse` could be empty while `rdeVersionInUse` should always be the entity type version of the RDE (it always be non-empty).

I used  `vcdCluster.Status.RdeVersionInUse` here for consistency. Let me know your thoughts. Thanks Aniruddha!
</blockquote></details>

I think what Aniruddha meant was - to use the variable `rdeVersionInUse` that is already assigned to _VCDCluster.Status.RdeVersionInUse_ somewhere up in the code.

There are two things
1. RDE version in use for a given Cluster - _VcdCluster.Status.RdeVersionInUse_
2. RDE version in use for a given CAPVCD product version - _rdeType.CapvcdREDTypeVersion_, which is always the latest 

@ymo24 If we are creating variables out of the above, please ensure variable names are distinguishable, something like below wherever appropriate.

rdeVersionInUseByCluster
rdeVersionInUseByCAPVCD
___
*[`pkg/capisdk/defined_entity.go` line 128 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NWEJZjR7LJQnsybhr6L:-NWEJZjR7LJQnsybhr6M:b-qxxpkt) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/832e86f714556358e3c7a934a2d12c2de1c5d91f/pkg/capisdk/defined_entity.go#L128)):*
> ```Go
> }
> 
> func CheckIfRdeVersionNeedsUpgraded(srcRdeTypeVersion string, tgtRdeTypeVersion string) bool {
> ```

nit: checkIfClusterRdeNeedsUpgrade
___
*[`pkg/capisdk/defined_entity.go` line 131 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NWEJkNhA4PgLmqmfrE_:-NWEJkNhA4PgLmqmfrEa:b3ecjp0) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/832e86f714556358e3c7a934a2d12c2de1c5d91f/pkg/capisdk/defined_entity.go#L131)):*
> ```Go
> 	entityTypeSemVer, err := semver.New(srcRdeTypeVersion)
> 	if err != nil {
> 		klog.Errorf("fail to convert [%s] into a standard version: [%v]", srcRdeTypeVersion, err)
> ```

Failed to convert RDE version [%s] into a semantic version.....
___
*[`pkg/capisdk/defined_entity.go` line 376 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NWEKo5Y2Ze_M3S_UaQN:-NWEKo5Y2Ze_M3S_UaQO:bak702n) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/832e86f714556358e3c7a934a2d12c2de1c5d91f/pkg/capisdk/defined_entity.go#L376)):*
> ```Go
> 		return false
> 	}
> 	// if the vcdKeSpec section is present, then the cluster is not managed by CSE
> ```

If vcdKE spec section is present, then the cluster is not managed by standalone capvcd.


<!-- Sent from Reviewable.io -->

2023-05-25 23:07 UTC, ymo24 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454)* status: 0 of 2 files reviewed, 8 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`pkg/capisdk/defined_entity.go` line 128 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NWEJZjR7LJQnsybhr6L:-NWK9cY28aq4waOhzh2T:btmlils) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/832e86f714556358e3c7a934a2d12c2de1c5d91f/pkg/capisdk/defined_entity.go#L128)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

nit: checkIfClusterRdeNeedsUpgrade
</blockquote></details>

Thanks for catching
___
*[`pkg/capisdk/defined_entity.go` line 131 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NWEJkNhA4PgLmqmfrE_:-NWK9b0lDfHhiX3Espf1:bc02wc4) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/832e86f714556358e3c7a934a2d12c2de1c5d91f/pkg/capisdk/defined_entity.go#L131)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Failed to convert RDE version [%s] into a semantic version.....
</blockquote></details>

Thanks Sahithi
___
*[`pkg/capisdk/defined_entity.go` line 376 at r3](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NWEKo5Y2Ze_M3S_UaQN:-NWK9ZU7AMJQ6NkcOvbk:b-vpp83g) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/832e86f714556358e3c7a934a2d12c2de1c5d91f/pkg/capisdk/defined_entity.go#L376)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

If vcdKE spec section is present, then the cluster is not managed by standalone capvcd.
</blockquote></details>

Thanks, Sahithi


<!-- Sent from Reviewable.io -->

2023-05-30 17:16 UTC, Anirudh9794 requested changes
> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454)* status: all files reviewed, 11 unresolved discussions (waiting on @sahithi and @ymo24)

___
*[`controllers/vcdcluster_controller.go` line 777 at r4](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NWhcrt73rdvOmR1UYyR:-NWhcrt73rdvOmR1UYyS:boq5i2f) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/a4d6e7fe67b6f06890f9aec30b913b2d47b11b4a/controllers/vcdcluster_controller.go#L777)):*
> ```Go
> 					log.Info("RDE for the cluster is already present; skipping RDE creation", "InfraId",
> 						definedEntities.Values[0].Id)
> 					infraID = definedEntities.Values[0].Id
> ```

we should also be setting  the `rdeVersionInUseByCluster` to `definedEntities.Values[0].entityTypeVersion`
___
*[`controllers/vcdcluster_controller.go` line 780 at r4](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NWhcfuf8Su2J0RserGd:-NWhcfuf8Su2J0RserGe:b-6xwufz) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/a4d6e7fe67b6f06890f9aec30b913b2d47b11b4a/controllers/vcdcluster_controller.go#L780)):*
> ```Go
> 				}
> 			}
> 			rdeVersionInUseByCluster = rdeType.CapvcdRDETypeVersion
> ```

Since we are now making a call using the DefaultMajorVersion in 
```
			definedEntities, resp, err := workloadVCDClient.APIClient.DefinedEntityApi.GetDefinedEntitiesByEntityType(ctx,
				capisdk.CAPVCDTypeVendor, capisdk.CAPVCDTypeNss, capisdk.CAPVCDEntityTypeDefaultMajorVersion, org.Org.ID, 1, 25, nameFilter)

```
we cannot set the `rdeVersionInUseByCluster` directly to `rdeType.CapvcdRDETypeVersion` when we are not creating an RDE but using an existing RDE.

The statement
```
rdeVersionInUseByCluster = rdeType.CapvcdRDETypeVersion
```
should move to the `if` part


<!-- Sent from Reviewable.io -->

2023-05-30 19:10 UTC, ymo24 reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454)* status: all files reviewed, 11 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[`controllers/vcdcluster_controller.go` line 821 at r1](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NW9vZMjDFzBhvvXMMFf:-NWi3HGC1Vg770q7MGOv:bc02wc4) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/e7690aac99a6a18648b51164eddaa12967844126/controllers/vcdcluster_controller.go#L821)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I think what Aniruddha meant was - to use the variable `rdeVersionInUse` that is already assigned to _VCDCluster.Status.RdeVersionInUse_ somewhere up in the code.

There are two things
1. RDE version in use for a given Cluster - _VcdCluster.Status.RdeVersionInUse_
2. RDE version in use for a given CAPVCD product version - _rdeType.CapvcdREDTypeVersion_, which is always the latest 

@ymo24 If we are creating variables out of the above, please ensure variable names are distinguishable, something like below wherever appropriate.

rdeVersionInUseByCluster
rdeVersionInUseByCAPVCD




</blockquote></details>

Thanks Sahithi
___
*[`controllers/vcdcluster_controller.go` line 701 at r4](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NWhUHjbANRjeiOMIXYX:-NWi38XfA5TTDQiHs67t:b-5r9ta5) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/a4d6e7fe67b6f06890f9aec30b913b2d47b11b4a/controllers/vcdcluster_controller.go#L701)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

// rdeVersionInUseByCluster is the current version of the RDE associated with the cluster. Note that this version can be different from the latest RDE version used by the CAPVCD product. In such cases, RDE version of the cluster will be upgraded to the latest RDE version used by CAPVCD.

Please add the above comment.
</blockquote></details>

Already added that. Thanks, Sahithi
___
*[`controllers/vcdcluster_controller.go` line 777 at r4](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NWhcrt73rdvOmR1UYyR:-NWi3BD_AWBvFDrB6mQl:bu6w0ru) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/a4d6e7fe67b6f06890f9aec30b913b2d47b11b4a/controllers/vcdcluster_controller.go#L777)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

we should also be setting  the `rdeVersionInUseByCluster` to `definedEntities.Values[0].entityTypeVersion`
</blockquote></details>

Thanks for the catching. Thanks, Aniruddha
___
*[`controllers/vcdcluster_controller.go` line 780 at r4](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-NWhcfuf8Su2J0RserGd:-NWi3E_6AYPRf61Uifnp:bzg28w6) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/a4d6e7fe67b6f06890f9aec30b913b2d47b11b4a/controllers/vcdcluster_controller.go#L780)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Since we are now making a call using the DefaultMajorVersion in 
```
			definedEntities, resp, err := workloadVCDClient.APIClient.DefinedEntityApi.GetDefinedEntitiesByEntityType(ctx,
				capisdk.CAPVCDTypeVendor, capisdk.CAPVCDTypeNss, capisdk.CAPVCDEntityTypeDefaultMajorVersion, org.Org.ID, 1, 25, nameFilter)

```
we cannot set the `rdeVersionInUseByCluster` directly to `rdeType.CapvcdRDETypeVersion` when we are not creating an RDE but using an existing RDE.

The statement
```
rdeVersionInUseByCluster = rdeType.CapvcdRDETypeVersion
```
should move to the `if` part
</blockquote></details>

Thanks Aniruddha


<!-- Sent from Reviewable.io -->

2023-05-30 19:18 UTC, Anirudh9794 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/454#-:-NWi59lHAvjIlsezESOZ:bg7igkv)* status: all files reviewed, 11 unresolved discussions (waiting on @sahithi)



<!-- Sent from Reviewable.io -->

2023-05-30 19:32 UTC, merged