[CAFV-301] Update reference to v1.1.0 in README
vmware/cluster-api-provider-cloud-director pull request #499
Opened 2023-07-18 20:22 UTC by lzichong

## Description
Please provide a brief description of the changes proposed in this Pull Request

- Update reference to v1.1.0 in README

## Checklist
- [ ] tested locally
- [ ] updated any relevant dependencies
- [ ] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [ ] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

2023-07-20 20:32 UTC, sahithi requested changes
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/499)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @lzichong and @rocknes)

___
*[`docs/CLUSTERCTL.md` line 23 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/499#-N_ozk2g9k0NqgN1QnyF:-N_ozk2h-QGgWkln9MTf:bre4ziz) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/becf6d2cfd20f2974718965cb12c95ecfe52ea39/docs/CLUSTERCTL.md#L23)):*
> ```Markdown
> 4. Copy [clusterctl.yaml](https://github.com/vmware/cluster-api-provider-cloud-director/blob/main/templates/clusterctl.yaml) to `~/.cluster-api/clusterctl.yaml`
> 5. Copy [infrastructure-components.yaml](https://github.com/vmware/cluster-api-provider-cloud-director/blob/main/templates/infrastructure-components.yaml) to `~/infrastructure-vcd/v1.1.0/`
> 6. Update the `providers.url` in `~/.cluster-api/clusterctl.yaml` to `~/infrastructure-vcd/v1.1.0/infrastructure-components.yaml`
> ```

We don't need to remove the entire section in the main. I intentionally left in main as-is. If someone wants to run from main branch, they need to do these steps. They need to get the infra-components.yaml from the main branch itself.

My intent to check clusterctl.md was to see if there are any broken links. If none, nothing needs to be done.


<!-- Sent from Reviewable.io -->

2023-07-20 20:53 UTC, lzichong reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/499)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @rocknes and @sahithi)

___
*[`docs/CLUSTERCTL.md` line 23 at r2](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/499#-N_ozk2g9k0NqgN1QnyF:-N_p3mQY4tIYv5gYHa5f:b-d4tn5t) ([raw file](https://github.com/vmware/cluster-api-provider-cloud-director/blob/becf6d2cfd20f2974718965cb12c95ecfe52ea39/docs/CLUSTERCTL.md#L23)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We don't need to remove the entire section in the main. I intentionally left in main as-is. If someone wants to run from main branch, they need to do these steps. They need to get the infra-components.yaml from the main branch itself.

My intent to check clusterctl.md was to see if there are any broken links. If none, nothing needs to be done.
</blockquote></details>

I have reverted the commit back to original state, I intentionally left it out initially as it had no broken links so I should have clarified. Sorry about that! Thanks Sahithi!


<!-- Sent from Reviewable.io -->

2023-07-24 19:22 UTC, rocknes approved these changes

2023-07-24 19:24 UTC, Anirudh9794 approved these changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/499)* status: all files reviewed, 1 unresolved discussion (waiting on @lzichong)



<!-- Sent from Reviewable.io -->

2023-07-24 19:26 UTC, merged