CAPI-1.7.4: Move core-CAPI dependencies to v1.7.4.
vmware/cluster-api-provider-cloud-director pull request #659
Opened 2024-10-03 18:44 UTC by arunmk

## Description
Please provide a brief description of the changes proposed in this Pull Request
- Imported core CAPI 1.7.4 and made changes needed since some of the methods changed. This upgrade also removed v1alpha4 compatibility since core-capi removed it fro v1.7.0 onwards.

## Checklist
- [X] tested locally
- [X] updated any relevant dependencies
- [X] updated any relevant documentation or examples

## API Changes
Are there API changes?
- [ ] Yes
- [X] No

If yes, please fill in the below

1. Updated conversions?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
2. Updated CRDs?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
3. Updated infrastructure-components.yaml?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
4. Updated `./examples/capi-quickstart.yaml`?
    - [ ] Yes
    - [ ] No
    - [ ] N/A
5. Updated necessary files under `./infrastructure-vcd/v1.0.0/`?
   - [ ] Yes
   - [ ] No
   - [ ] N/A

## Issue
If applicable, please reference the relevant issue

Fixes #

2024-10-03 18:51 UTC, lzichong approved these changes
LGTM, I think we can remove the .DS_STORE file in controllers

2024-10-03 18:52 UTC, arunmk commented on main.go
> +	metricsAddr          string
This variable can be removed

2024-10-04 16:42 UTC, sakthisunda requested changes
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/659)* status: 0 of 467 files reviewed, 2 unresolved discussions (waiting on @arunmk, @rocknes, and @sahithi)

*[a discussion](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/659#-O8NOvOeBBJEGfmBKPwN:-O8NOvOeBBJEGfmBKPwO:bh4kc8b) (no related file):*
should folder api/v1alpha4 also be removed ?

___


<!-- Sent from Reviewable.io -->

2024-10-04 16:42 UTC, sakthisunda approved these changes
> *[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/659)* status: 0 of 467 files reviewed, 1 unresolved discussion (waiting on @rocknes and @sahithi)



<!-- Sent from Reviewable.io -->

2024-10-04 17:54 UTC, arunmk commented
> > _[Reviewable](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/659)_ status: 0 of 467 files reviewed, 2 unresolved discussions (waiting on @arunmk, @rocknes, and @sahithi)
> 
> _[a discussion](https://reviewable.io/reviews/vmware/cluster-api-provider-cloud-director/659#-O8NOvOeBBJEGfmBKPwN:-O8NOvOeBBJEGfmBKPwO:bh4kc8b) (no related file):_ should folder api/v1alpha4 also be removed ?

@sakthisunda I have removed it but github does not show it well. For verification, please look at the branch itself: https://github.com/arunmk/cluster-api-provider-cloud-director/tree/ak/capi-1.7.4/api

2024-10-04 18:31 UTC, lzichong approved these changes
Updated changes LGTM

2024-10-04 18:32 UTC, rocknes approved these changes
LGTM

2024-10-04 18:36 UTC, sakthisunda commented
@arunmk Should there also be new files templates/cluster-template-crs.yaml and templates/cluster-template.yaml  for TKG 2.5.2 supported kubernetes versions ?

2024-10-04 18:52 UTC, merged

2024-10-08 16:21 UTC, sahithi commented on templates/infrastructure-components.yaml
nit: CRDs seem to have v1alpha4 labels. We can remove them for the correctness sake.

2024-10-08 16:23 UTC, sahithi reviewed
Please update metadata.yaml to remove v1alpha4